#!/usr/bin/env pwsh
# Tests uninstall.ps1 agent-hook removal parity (.5.1): Gemini (generalized
# Remove-DcgHooksFromJsonFile), Cursor (hooks.json + bridge), Copilot (user-level
# field-level), agy/Grok (PreToolUse/Bash shape). Builds the post-install state
# (with a coexisting hook) and asserts dcg is removed while coexisting survives.

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)

$script:failures = 0
function Check([bool]$cond, [string]$msg) {
    if ($cond) { Write-Host "  ok: $msg" } else { Write-Host "  FAIL: $msg" -ForegroundColor Red; $script:failures++ }
}
function New-Tmp { Join-Path ([System.IO.Path]::GetTempPath()) ("dcg_uninst_" + [Guid]::NewGuid().ToString('N')) }
function Test-NoBom([string]$p) {
    $b = [System.IO.File]::ReadAllBytes($p)
    -not ($b.Length -ge 3 -and $b[0] -eq 0xEF -and $b[1] -eq 0xBB -and $b[2] -eq 0xBF)
}
$dcg = "C:\Users\O'Brien\.local\bin\dcg.exe"
$escapedDcg = $dcg.Replace("'", "''")

$ompSelectorNames = @('OMP_PROFILE', 'PI_PROFILE', 'PI_CONFIG_DIR', 'PI_CODING_AGENT_DIR')
$savedOmpSelectors = @{}
foreach ($name in $ompSelectorNames) {
    $savedOmpSelectors[$name] = [Environment]::GetEnvironmentVariable($name, 'Process')
    # Seed first so this fence is mutation-sensitive on hosts whose ambient
    # environment happens to be clean.
    Microsoft.PowerShell.Management\Set-Item -LiteralPath "Env:$name" -Value "dcg-test-ambient-$name"
}
foreach ($name in $ompSelectorNames) {
    Microsoft.PowerShell.Management\Remove-Item -LiteralPath "Env:$name" -ErrorAction SilentlyContinue
}

try {
    $unclearedOmpSelectors = @($ompSelectorNames | Where-Object {
        Test-Path -LiteralPath "Env:$_"
    })
    if ($unclearedOmpSelectors.Count -ne 0) {
        throw "OMP test selector fence failed: $($unclearedOmpSelectors -join ', ')"
    }
    Check $true "OMP path/profile selectors are scrubbed before loading uninstaller functions"

    . (Join-Path $repoRoot 'uninstall.ps1') -LoadFunctionsOnly

Write-Host "Test 0: Claude (Bash|PowerShell wrapper) - remove dcg, keep Bash-only hook"
$h0 = New-Tmp; New-Item -ItemType Directory -Path $h0 -Force | Out-Null
try {
    $f = Join-Path $h0 'settings.json'
    @{ hooks = @{ PreToolUse = @(
        @{ matcher = 'Bash|PowerShell'; hooks = @(
            @{ type = 'command'; command = "& '$escapedDcg'"; shell = 'powershell' }) },
        @{ matcher = 'Bash'; hooks = @(
            @{ type = 'command'; command = 'keep-bash-only' }) })
    } } | ConvertTo-Json -Depth 20 | Set-Content $f
    Check ((Remove-DcgHooksFromJsonFile -Path $f) -eq $true) "Claude: returns true (removed)"
    $cfg = Get-Content -Raw $f | ConvertFrom-Json
    $entries = @($cfg.hooks.PreToolUse)
    Check ($entries.Count -eq 1) "Claude: emptied combined matcher pruned"
    Check ($entries[0].matcher -eq 'Bash') "Claude: Bash-only matcher preserved"
    Check ($entries[0].hooks[0].command -eq 'keep-bash-only') "Claude: coexisting command preserved"
} finally { Remove-Item -Recurse -Force $h0 -ErrorAction SilentlyContinue }

Write-Host "Test 1: Gemini (BeforeTool/run_shell_command) - remove dcg, keep coexisting"
$h1 = New-Tmp; New-Item -ItemType Directory -Path (Join-Path $h1 '.gemini') -Force | Out-Null
try {
    $f = Join-Path $h1 '.gemini/settings.json'
    @{ hooks = @{ BeforeTool = @(@{ matcher = 'run_shell_command'; hooks = @(
        @{ command = $dcg; name = 'dcg'; timeout = 5000 }, @{ command = 'other-tool'; name = 'other' }) }) } } |
        ConvertTo-Json -Depth 20 | Set-Content $f
    Check ((Remove-DcgHooksFromJsonFile -Path $f -EventName 'BeforeTool' -DeleteEmptyFile) -eq $true) "returns true (removed)"
    Check (Test-NoBom $f) "rewritten without BOM"
    $cmds = @((Get-Content -Raw $f | ConvertFrom-Json).hooks.BeforeTool[0].hooks | ForEach-Object { $_.command })
    Check (-not ($cmds -contains $dcg)) "dcg removed"
    Check ($cmds -contains 'other-tool') "coexisting hook preserved"
} finally { Remove-Item -Recurse -Force $h1 -ErrorAction SilentlyContinue }

Write-Host "Test 2: Cursor (hooks.json + bridge) - delete bridge, remove entry, keep coexisting"
$h2 = New-Tmp
try {
    $hookDir = Join-Path $h2 '.cursor/hooks'; New-Item -ItemType Directory -Path $hookDir -Force | Out-Null
    $bridge = Join-Path $hookDir 'dcg-pre-shell.ps1'
    Set-Content -Path $bridge -Value '# dcg-cursor-hook: generated by dcg installer'
    $launcher = "powershell -NoProfile -ExecutionPolicy Bypass -File `"$bridge`""
    @{ version = 1; hooks = @{ beforeShellExecution = @(@{ command = $launcher }, @{ command = 'other-tool --x' }) } } |
        ConvertTo-Json -Depth 20 | Set-Content (Join-Path $h2 '.cursor/hooks.json')
    Check ((Unconfigure-CursorHook -HomeDir $h2) -eq $true) "returns true (removed)"
    Check (-not (Test-Path $bridge)) "dcg bridge script deleted"
    $cfg = Get-Content -Raw (Join-Path $h2 '.cursor/hooks.json') | ConvertFrom-Json
    $cmds = @($cfg.hooks.beforeShellExecution | ForEach-Object { $_.command })
    Check (-not ($cmds | Where-Object { $_ -match 'dcg-pre-shell' })) "dcg launcher entry removed"
    Check ($cmds -contains 'other-tool --x') "coexisting hook preserved"
} finally { Remove-Item -Recurse -Force $h2 -ErrorAction SilentlyContinue }

Write-Host "Test 3: Cursor dcg-only file is deleted on clean round-trip"
$h3 = New-Tmp
try {
    $hookDir = Join-Path $h3 '.cursor/hooks'; New-Item -ItemType Directory -Path $hookDir -Force | Out-Null
    $bridge = Join-Path $hookDir 'dcg-pre-shell.ps1'
    Set-Content -Path $bridge -Value '# dcg-cursor-hook: x'
    $launcher = "powershell -NoProfile -ExecutionPolicy Bypass -File `"$bridge`""
    @{ version = 1; hooks = @{ beforeShellExecution = @(@{ command = $launcher }) } } |
        ConvertTo-Json -Depth 20 | Set-Content (Join-Path $h3 '.cursor/hooks.json')
    [void](Unconfigure-CursorHook -HomeDir $h3)
    Check (-not (Test-Path (Join-Path $h3 '.cursor/hooks.json'))) "dcg-only hooks.json deleted (clean round-trip)"
} finally { Remove-Item -Recurse -Force $h3 -ErrorAction SilentlyContinue }

Write-Host "Test 4: Copilot (user-level, field-level) - strip dcg field, keep coexisting"
$r4 = New-Tmp
try {
    $hookDir = Join-Path $r4 'hooks'; New-Item -ItemType Directory -Path $hookDir -Force | Out-Null
    @{ version = 1; hooks = @{ preToolUse = @(
        @{ type = 'command'; bash = $dcg; powershell = $dcg; cwd = '.'; timeoutSec = 30 },
        @{ type = 'command'; bash = $dcg; powershell = 'my-formatter' },   # dcg bash + foreign powershell
        @{ type = 'command'; bash = 'linter'; powershell = 'linter.exe' }) } } |
        ConvertTo-Json -Depth 20 | Set-Content (Join-Path $hookDir 'dcg.json')
    Check ((Unconfigure-CopilotHook -CopilotHome $r4) -eq $true) "returns true (removed)"
    $cfg = Get-Content -Raw (Join-Path $hookDir 'dcg.json') | ConvertFrom-Json
    $entries = @($cfg.hooks.preToolUse)
    Check ($null -eq ($entries | Where-Object { $_.bash -eq $dcg -or $_.powershell -eq $dcg })) "all dcg fields stripped"
    $formatter = @($entries | Where-Object { $_.powershell -eq 'my-formatter' })[0]
    Check (($null -ne $formatter) -and ($null -eq $formatter.PSObject.Properties['bash'])) "entry kept with dcg bash field stripped, foreign powershell retained"
    Check (@($entries | Where-Object { $_.bash -eq 'linter' }).Count -eq 1) "fully-coexisting linter entry intact"
} finally { Remove-Item -Recurse -Force $r4 -ErrorAction SilentlyContinue }

Write-Host "Test 5: agy (~/.gemini/config/hooks.json, PreToolUse/Bash) - remove dcg, keep coexisting"
$h5 = New-Tmp
try {
    $cfgDir = Join-Path $h5 '.gemini/config'; New-Item -ItemType Directory -Path $cfgDir -Force | Out-Null
    $f = Join-Path $cfgDir 'hooks.json'
    @{ hooks = @{ PreToolUse = @(@{ matcher = 'Bash'; hooks = @(
        @{ type = 'command'; command = 'dcg' }, @{ type = 'command'; command = 'keep-me' }) }) } } |
        ConvertTo-Json -Depth 20 | Set-Content $f
    Check ((Remove-DcgHooksFromJsonFile -Path $f -DeleteEmptyFile) -eq $true) "agy: returns true (removed)"
    $cmds = @((Get-Content -Raw $f | ConvertFrom-Json).hooks.PreToolUse[0].hooks | ForEach-Object { $_.command })
    Check (($cmds -notcontains 'dcg') -and ($cmds -contains 'keep-me')) "agy: dcg gone, coexisting kept"
} finally { Remove-Item -Recurse -Force $h5 -ErrorAction SilentlyContinue }

Write-Host "Test 6: dcg-only file is deleted (Codex/agy style, -DeleteEmptyFile)"
$h6 = New-Tmp; New-Item -ItemType Directory -Path $h6 -Force | Out-Null
try {
    $f = Join-Path $h6 'hooks.json'
    @{ hooks = @{ PreToolUse = @(@{ matcher = 'Bash'; hooks = @(@{ type = 'command'; command = 'dcg' }) }) } } |
        ConvertTo-Json -Depth 20 | Set-Content $f
    [void](Remove-DcgHooksFromJsonFile -Path $f -DeleteEmptyFile)
    Check (-not (Test-Path $f)) "dcg-only file deleted"
} finally { Remove-Item -Recurse -Force $h6 -ErrorAction SilentlyContinue }

Write-Host "Test 7: invalid JSON is left unchanged"
$h7 = New-Tmp; New-Item -ItemType Directory -Path $h7 -Force | Out-Null
try {
    $f = Join-Path $h7 'hooks.json'; Set-Content -Path $f -Value '{ not json' -NoNewline
    Check ((Remove-DcgHooksFromJsonFile -Path $f) -eq $false) "invalid JSON -> false (untouched)"
    Check ((Get-Content -Raw $f) -eq '{ not json') "invalid file content unchanged"
} finally { Remove-Item -Recurse -Force $h7 -ErrorAction SilentlyContinue }

Write-Host "Test 8: wrong-matcher dcg hook is removed, sibling survives"
$h8 = New-Tmp; New-Item -ItemType Directory -Path $h8 -Force | Out-Null
try {
    $f = Join-Path $h8 'settings.json'
    @{ hooks = @{ PreToolUse = @(@{ matcher = 'Write'; hooks = @(
        @{ type = 'command'; command = $dcg },
        @{ type = 'command'; command = 'keep-write-hook' }) }) } } |
        ConvertTo-Json -Depth 20 | Set-Content $f
    Check ((Remove-DcgHooksFromJsonFile -Path $f) -eq $true) "wrong-matcher hook: returns true"
    $hooks = @((Get-Content -Raw $f | ConvertFrom-Json).hooks.PreToolUse[0].hooks)
    Check ($hooks.Count -eq 1 -and $hooks[0].command -eq 'keep-write-hook') "wrong-matcher sibling preserved"
} finally { Remove-Item -Recurse -Force $h8 -ErrorAction SilentlyContinue }

Write-Host "Test 9: keep-config and keep-history are independent"
$h9 = New-Tmp
try {
    $config = Join-Path $h9 '.config/dcg'
    $data = Join-Path $h9 '.local/share/dcg'
    New-Item -ItemType Directory -Path $config -Force | Out-Null
    New-Item -ItemType Directory -Path $data -Force | Out-Null
    Set-Content (Join-Path $config 'config.toml') 'mode = "deny"'
    Set-Content (Join-Path $config 'history.db') 'history'
    Set-Content (Join-Path $config 'history.db-wal') 'wal'
    New-Item -ItemType Directory -Path (Join-Path $config 'backups') -Force | Out-Null
    Set-Content (Join-Path $config 'backups/dcg.exe') 'backup'
    Set-Content (Join-Path $data 'blocked.log') 'log'
    Remove-DcgStateDirectories -ConfigDir $config -DataDir $data -KeepHistory
    Check (-not (Test-Path (Join-Path $config 'config.toml'))) "KeepHistory removes config"
    Check (Test-Path (Join-Path $config 'history.db')) "KeepHistory preserves history database"
    Check (Test-Path (Join-Path $config 'history.db-wal')) "KeepHistory preserves SQLite sidecar"
    Check (Test-Path (Join-Path $config 'backups/dcg.exe')) "KeepHistory preserves release backups"
    Check (Test-Path $data) "KeepHistory preserves data directory"

    Set-Content (Join-Path $config 'config.toml') 'mode = "deny"'
    Remove-DcgStateDirectories -ConfigDir $config -DataDir $data -KeepConfig
    Check (Test-Path (Join-Path $config 'config.toml')) "KeepConfig preserves config"
    Check (-not (Test-Path (Join-Path $config 'history.db'))) "KeepConfig removes history database"
    Check (-not (Test-Path (Join-Path $config 'history.db-wal'))) "KeepConfig removes SQLite sidecar"
    Check (-not (Test-Path (Join-Path $config 'backups'))) "KeepConfig removes release backups"
    Check (-not (Test-Path $data)) "KeepConfig removes data directory"
} finally { Remove-Item -Recurse -Force $h9 -ErrorAction SilentlyContinue }

Write-Host "Test 10: Copilot PascalCase PreToolUse dcg entry removed, coexisting survives (#253)"
$h10 = New-Tmp
try {
    $hookDir = Join-Path $h10 'hooks'; New-Item -ItemType Directory -Path $hookDir -Force | Out-Null
    @{ version = 1; hooks = @{ PreToolUse = @(
        @{ type = 'command'; bash = $dcg; powershell = $dcg; cwd = '.'; timeoutSec = 30 },
        @{ type = 'command'; bash = 'linter'; powershell = 'linter.exe' }) } } |
        ConvertTo-Json -Depth 20 | Set-Content (Join-Path $hookDir 'dcg.json')
    Check ((Unconfigure-CopilotHook -CopilotHome $h10) -eq $true) "PascalCase key: returns true (removed)"
    $cfg = Get-Content -Raw (Join-Path $hookDir 'dcg.json') | ConvertFrom-Json
    $preKeys = @($cfg.hooks.PSObject.Properties.Name | Where-Object { $_.ToLowerInvariant() -eq 'pretooluse' })
    Check (($preKeys.Count -eq 1) -and ($preKeys[0] -ceq 'PreToolUse')) "existing PascalCase spelling kept (got: $($preKeys -join ', '))"
    $entries = @($cfg.hooks.PSObject.Properties['PreToolUse'].Value)
    Check ($null -eq ($entries | Where-Object { $_.bash -eq $dcg -or $_.powershell -eq $dcg })) "PascalCase dcg entry removed"
    Check (@($entries | Where-Object { $_.bash -eq 'linter' }).Count -eq 1) "coexisting non-dcg entry survives"
} finally { Remove-Item -Recurse -Force $h10 -ErrorAction SilentlyContinue }

Write-Host "Test 11: Oh My Pi marker-owned extension removed, user extension preserved"
$h11 = New-Tmp
try {
    $extDir = Join-Path (Join-Path (Join-Path $h11 '.omp') 'agent') 'extensions'
    New-Item -ItemType Directory -Path $extDir -Force | Out-Null
    $extension = Join-Path $extDir 'dcg-guard.ts'
    Set-Content -Path $extension -Value '// dcg-omp-extension: generated'
    Check ((Unconfigure-OmpExtension -HomeDir $h11 -RepoRoot $h11) -eq $true) "OMP: marker-owned extension removed"
    Check (-not (Test-Path $extension)) "OMP: generated extension no longer exists"

    Set-Content -Path $extension -Value 'export default function mine() {}'
    Check ((Unconfigure-OmpExtension -HomeDir $h11 -RepoRoot $h11) -eq $false) "OMP: user extension not claimed"
    Check (Test-Path $extension) "OMP: user-authored extension preserved"
} finally { Remove-Item -Recurse -Force $h11 -ErrorAction SilentlyContinue }

Write-Host "Test 12: Oh My Pi inactive profiles and repository-root extension are removed"
$h12 = New-Tmp
$savedLocation = (Get-Location).Path
try {
    $defaultExtension = Join-Path $h12 '.omp/agent/extensions/dcg-guard.ts'
    $workExtension = Join-Path $h12 '.omp/profiles/work/agent/extensions/dcg-guard.ts'
    $teamExtension = Join-Path $h12 '.omp/profiles/team/agent/extensions/dcg-guard.ts'
    $userExtension = Join-Path $h12 '.omp/profiles/personal/agent/extensions/dcg-guard.ts'
    $repo = Join-Path $h12 'repo'
    $nested = Join-Path $repo 'a/b'
    $projectExtension = Join-Path $repo '.omp/extensions/dcg-guard.ts'
    foreach ($path in @($defaultExtension, $workExtension, $teamExtension, $userExtension, $projectExtension)) {
        New-Item -ItemType Directory -Force -Path (Split-Path -Parent $path) | Out-Null
    }
    New-Item -ItemType Directory -Force -Path (Join-Path $repo '.git'), $nested | Out-Null
    foreach ($path in @($defaultExtension, $workExtension, $teamExtension, $projectExtension)) {
        Set-Content -Path $path -Value '// dcg-omp-extension: generated'
    }
    Set-Content -Path $userExtension -Value 'export default function mine() {}'

    Set-Location -LiteralPath $nested
    Check ((Unconfigure-OmpExtension -HomeDir $h12) -eq $true) "OMP: profile/project sweep removed generated extensions"
    Check (-not (Test-Path $defaultExtension)) "OMP: default extension removed"
    Check (-not (Test-Path $workExtension)) "OMP: inactive work profile removed"
    Check (-not (Test-Path $teamExtension)) "OMP: inactive team profile removed"
    Check (-not (Test-Path $projectExtension)) "OMP: repository-root extension removed from nested cwd"
    Check (Test-Path $userExtension) "OMP: inactive user-authored extension preserved"
} finally {
    Set-Location $savedLocation
    Remove-Item -Recurse -Force $h12 -ErrorAction SilentlyContinue
}

Write-Host "Test 13: Oh My Pi project cleanup treats wildcard characters literally"
$h13 = New-Tmp
$savedLocation = (Get-Location).Path
try {
    $repo = Join-Path $h13 'repo[one]'
    $nested = Join-Path $repo 'nested'
    $projectExtension = Join-Path $repo '.omp/extensions/dcg-guard.ts'
    [void][System.IO.Directory]::CreateDirectory((Join-Path $repo '.git'))
    [void][System.IO.Directory]::CreateDirectory($nested)
    [void][System.IO.Directory]::CreateDirectory((Split-Path -Parent $projectExtension))
    [System.IO.File]::WriteAllText($projectExtension, '// dcg-omp-extension: generated')

    Set-Location -LiteralPath $nested
    Check ((Get-DcgRepositoryRoot) -eq $repo) "OMP: repository root with brackets is discovered literally"
    Check ((Unconfigure-OmpExtension -HomeDir $h13) -eq $true) "OMP: bracketed project extension is removed"
    Check (-not (Test-Path -LiteralPath $projectExtension)) "OMP: no project extension remains"
} finally {
    Set-Location $savedLocation
    Remove-Item -Recurse -Force $h13 -ErrorAction SilentlyContinue
}

Write-Host "Test 14: Oh My Pi cleanup does not claim a failed deletion"
$h14 = New-Tmp
try {
    $defaultExtension = Join-Path $h14 '.omp/agent/extensions/dcg-guard.ts'
    $profileExtension = Join-Path $h14 '.omp/profiles/work/agent/extensions/dcg-guard.ts'
    [void][System.IO.Directory]::CreateDirectory((Split-Path -Parent $defaultExtension))
    [void][System.IO.Directory]::CreateDirectory((Split-Path -Parent $profileExtension))
    [System.IO.File]::WriteAllText($defaultExtension, '// dcg-omp-extension: generated')
    [System.IO.File]::WriteAllText($profileExtension, '// dcg-omp-extension: generated')

    function Remove-Item {
        [CmdletBinding()]
        param([string]$LiteralPath, [switch]$Force)
        if ($LiteralPath -eq $profileExtension) { throw "simulated locked file: $LiteralPath" }
        Microsoft.PowerShell.Management\Remove-Item -LiteralPath $LiteralPath -Force:$Force
    }

    Check ((Unconfigure-OmpExtension -HomeDir $h14 -RepoRoot $h14) -eq $false) "OMP: partial deletion is not reported as complete"
    Check (-not (Test-Path -LiteralPath $defaultExtension)) "OMP: removable extension is still cleaned up"
    Check (Test-Path -LiteralPath $profileExtension) "OMP: failed deletion leaves the extension in place"
} finally {
    Microsoft.PowerShell.Management\Remove-Item -LiteralPath 'Function:\Remove-Item' -Force -ErrorAction SilentlyContinue
    Microsoft.PowerShell.Management\Remove-Item -LiteralPath $h14 -Recurse -Force -ErrorAction SilentlyContinue
}

Write-Host "Test 15: Oh My Pi cleanup does not claim success when profile enumeration fails"
$h15 = New-Tmp
try {
    $defaultExtension = Join-Path $h15 '.omp/agent/extensions/dcg-guard.ts'
    $profileExtension = Join-Path $h15 '.omp/profiles/work/agent/extensions/dcg-guard.ts'
    $profilesRoot = Join-Path $h15 '.omp/profiles'
    [void][System.IO.Directory]::CreateDirectory((Split-Path -Parent $defaultExtension))
    [void][System.IO.Directory]::CreateDirectory((Split-Path -Parent $profileExtension))
    [System.IO.File]::WriteAllText($defaultExtension, '// dcg-omp-extension: generated')
    [System.IO.File]::WriteAllText($profileExtension, '// dcg-omp-extension: generated')

    function Get-ChildItem {
        [CmdletBinding()]
        param([string]$LiteralPath, [switch]$Directory)
        if ($LiteralPath -eq $profilesRoot) { throw "simulated unreadable profiles directory: $LiteralPath" }
        Microsoft.PowerShell.Management\Get-ChildItem -LiteralPath $LiteralPath -Directory:$Directory -ErrorAction Stop
    }

    Check ((Unconfigure-OmpExtension -HomeDir $h15 -RepoRoot $h15) -eq $false) "OMP: profile enumeration failure is not reported as complete"
    Check (-not (Test-Path -LiteralPath $defaultExtension)) "OMP: known default extension is still cleaned up"
    Check (Test-Path -LiteralPath $profileExtension) "OMP: unenumerated profile extension remains in place"
} finally {
    Microsoft.PowerShell.Management\Remove-Item -LiteralPath 'Function:\Get-ChildItem' -Force -ErrorAction SilentlyContinue
    Microsoft.PowerShell.Management\Remove-Item -LiteralPath $h15 -Recurse -Force -ErrorAction SilentlyContinue
}

Write-Host "Test 16: Oh My Pi config root rejects Windows drive-qualified overrides"
$savedPiConfigDir = $env:PI_CONFIG_DIR
try {
    $env:PI_CONFIG_DIR = 'C:\omp-outside-home'
    $threw = $false
    try {
        [void](Get-OmpConfigRoot -HomeDir 'C:\Users\tester' -WindowsSemantics $true)
    } catch {
        $threw = $true
    }
    Check $threw "OMP: drive-qualified PI_CONFIG_DIR is rejected under Windows semantics"
} finally {
    $env:PI_CONFIG_DIR = $savedPiConfigDir
}

Write-Host "Test 17: Oh My Pi cleanup identifies marker inspection failures"
$h17 = New-Tmp
$savedWriteWarn = (Get-Command Write-Warn).ScriptBlock
try {
    $defaultExtension = Join-Path $h17 '.omp/agent/extensions/dcg-guard.ts'
    $profileExtension = Join-Path $h17 '.omp/profiles/work/agent/extensions/dcg-guard.ts'
    [void][System.IO.Directory]::CreateDirectory((Split-Path -Parent $defaultExtension))
    [void][System.IO.Directory]::CreateDirectory((Split-Path -Parent $profileExtension))
    [System.IO.File]::WriteAllText($defaultExtension, '// dcg-omp-extension: generated')
    [System.IO.File]::WriteAllText($profileExtension, '// dcg-omp-extension: generated')
    $script:ompInspectionWarning = ''

    function Get-Content {
        [CmdletBinding()]
        param([switch]$Raw, [string]$LiteralPath)
        if ($LiteralPath -eq $profileExtension) { throw "simulated unreadable marker: $LiteralPath" }
        Microsoft.PowerShell.Management\Get-Content -Raw:$Raw -LiteralPath $LiteralPath -ErrorAction Stop
    }
    function Write-Warn {
        param([string]$Message)
        $script:ompInspectionWarning = $Message
    }

    Check ((Unconfigure-OmpExtension -HomeDir $h17 -RepoRoot $h17) -eq $false) "OMP: marker inspection failure is not reported as complete"
    Check (-not (Test-Path -LiteralPath $defaultExtension)) "OMP: marker-readable extension is still cleaned up"
    Check (Test-Path -LiteralPath $profileExtension) "OMP: unreadable extension remains in place"
    Check ($script:ompInspectionWarning -like "Could not inspect Oh My Pi extension at ${profileExtension}:*") "OMP: warning distinguishes inspection from deletion failure"
} finally {
    Microsoft.PowerShell.Management\Remove-Item -LiteralPath 'Function:\Get-Content' -Force -ErrorAction SilentlyContinue
    Set-Item -LiteralPath 'Function:\Write-Warn' -Value $savedWriteWarn
    Microsoft.PowerShell.Management\Remove-Item -LiteralPath $h17 -Recurse -Force -ErrorAction SilentlyContinue
}
} finally {
    foreach ($name in $ompSelectorNames) {
        if ($null -eq $savedOmpSelectors[$name]) {
            Microsoft.PowerShell.Management\Remove-Item -LiteralPath "Env:$name" -ErrorAction SilentlyContinue
        } else {
            Microsoft.PowerShell.Management\Set-Item -LiteralPath "Env:$name" -Value $savedOmpSelectors[$name]
        }
    }
}

if ($script:failures -gt 0) { Write-Host "$script:failures FAILURE(S)" -ForegroundColor Red; exit 1 }
Write-Host "All uninstall parity tests passed." -ForegroundColor Green
